Repository 33RD-DO-SOPT-SOPKATHON-iOS-TEAM2/SOPKATHON-2-SERVER, pull requests merged in 2023-11, with the labels that each got.

#7 [FEAT] 익셉션 처리 로직 구현
  src/main/java/org/sopkathon/www/DoSoptSopkathon/exception/BaseCustomException.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/exception/ExceptionResponse.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/exception/ExceptionType.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/exception/GlobalExceptionHandler.java
Labels: FEAT, 준서✨️

#12 [FEAT] 전체 증서 조회 api 구현
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/controller/SharedCardController.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/controller/dto/GetSharedCardResponseDto.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/domain/repository/CardRepository.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/service/SharedCardService.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/user/controller/UserController.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/user/controller/dto/request/CreateUserRequestDto.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/user/service/UserService.java
Labels: FEAT, 하연✨️

#13 [DEPLOY] 1차 배포
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/sopkathon/www/DoSoptSopkathon/DoSoptSopkathonApplication.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/controller/CardController.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/controller/SharedCardController.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/controller/dto/GetSharedCardResponseDto.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/controller/dto/request/CreateCardRequestDto.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/controller/dto/response/GetCardResponseDto.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/domain/entity/Alcohol.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/domain/entity/Card.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/domain/entity/DressCode.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/domain/entity/Flower.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/domain/repository/CardRepository.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/exception/CardException.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/exception/CardExceptionType.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/service/CardService.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/service/SharedCardService.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/common/config/JpaAuditingConfig.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/common/domain/entity/BaseCreatedTimeEntity.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/exception/BaseCustomException.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/exception/ExceptionResponse.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/exception/ExceptionType.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/exception/GlobalExceptionHandler.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/user/controller/UserController.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/user/controller/dto/request/CreateUserRequestDto.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/user/domain/entity/Gender.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/user/domain/entity/User.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/user/domain/repository/UserRepository.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/user/exception/UserException.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/user/exception/UserExceptionType.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/user/service/UserService.java
  src/test/java/org/sopkathon/www/DoSoptSopkathon/DoSoptSopkathonApplicationTests.java
Labels: DEPLOY

#15 [ADD] 전체 증서 조회시 생성된 시간 내림차순으로 정렬
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/domain/repository/CardRepository.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/service/SharedCardService.java
Labels: ADD

#18 [ADD] 이미 증서를 등록한 경우 다시 등록하지 못하는 로직을 추가한다.
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/exception/CardExceptionType.java
  src/main/java/org/sopkathon/www/DoSoptSopkathon/card/service/CardService.java
Labels: ADD

#20 [ADD] 지원하지 않는 enum 값 넣었을 때 익셉션 처리
  src/main/java/org/sopkathon/www/DoSoptSopkathon/exception/GlobalExceptionHandler.java
Labels: ADD
